version: "3.9"

services:

  mongo:
    image: mongo:7
    container_name: mongo_healthcare
    restart: always
    command: ["mongod", "--auth"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - healthcare_network

  migration:
    build: .
    container_name: migration_script
    depends_on:
      - mongo
    env_file:
      - .env
    command: python migrate_to_mongo.py
    networks:
      - healthcare_network

volumes:
  mongo_data:

networks:
  healthcare_network:
    driver: bridge


